#ifndef GAME_STATE_H
#define GAME_STATE_H

typedef enum
{
    STATE_TITLE,
    STATE_ARCADE1,
    STATE_ARCADE2,
    STATE_BIOPOD,
    STATE_HYDROPONICSBAY,
    STATE_HANGARBAY,
    STATE_TRAININGDECK,
    STATE_REACTORCHAMBER,
    STATE_SLEEPINGQUARTERS,
    STATE_ARMORYVAULT,
    STATE_HOLODECK,
    STATE_MEDICALBAY,
    STATE_SCIENCELAB,
    STATE_QUIT
} GameState;

#endif
